export const Users = [
  {
    id: 1,
    profilePicture: "/assets/pics/ant.jpg",
    username: "Paul Rudd",
    online: true,
  },
  {
    id: 2,
    profilePicture: "/assets/pics/cap.jpg",
    username: "Chris Evans",
    online: false,
  },
  {
    id: 3,
    profilePicture: "/assets/pics/hawk.jpg",
    username: "Jeremy Renner",
    online: false,
  },
  {
    id: 4,
    profilePicture: "/assets/pics/hulk.jpg",
    username: "Mark Ruffalo",
    online: true,
  },
  {
    id: 5,
    profilePicture: "/assets/pics/loki.jpeg",
    username: "Tom Hiddleson",
    online: false,
  },
  {
    id: 6,
    profilePicture: "/assets/pics/marvel.jpg",
    username: "Brie Larson",
    online: true,
  },
  {
    id: 7,
    profilePicture: "/assets/pics/nat.jpg",
    username: "Scarlett Johansson",
    online: true,
  },
  {
    id: 8,
    profilePicture: "/assets/pics/pool.jpg",
    username: "Ryan Reynolds",
    online: false,
  },
  {
    id: 9,
    profilePicture: "/assets/pics/spider.jpg",
    username: "Tom Holland",
    online: true,
  },
  {
    id: 10,
    profilePicture: "/assets/pics/star.jpg",
    username: "Chris Pratt",
    online: true,
  },
  {
    id: 11,
    profilePicture: "/assets/pics/strange.jpg",
    username: "Benedict Cumberbatch",
    online: true,
  },
  {
    id: 12,
    profilePicture: "/assets/pics/thor.jpg",
    username: "Chris Hemsworth",
    online: false,
  },
  {
    id: 13,
    profilePicture: "/assets/pics/tony.jpg",
    username: "Robert Downey Jr.",
    online: true,
  },
  {
    id: 14,
    profilePicture: "/assets/pics/wanda.jpg",
    username: "Elizabeth Olsen",
    online: true,
  },
  {
    id: 15,
    profilePicture: "/assets/pics/wolv.jpg",
    username: "Hugh Jackman",
    online: false,
  },
  {
    id: 16,
    profilePicture: "/assets/myPic.jpg",
    username: "Arish",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "I love my daughter",
    photo: "/assets/posts/antman.jpg",
    userId: 1,
    like: 50,
    comment: 30,
    date: "5 mins ago",
  },
  {
    id: 2,
    desc: "i can do this all day",
    photo: "/assets/posts/captainAmerica.jpg",
    userId: 2,
    like: 100,
    comment: 60,
    date: "15 mins ago",
  },
  {
    id: 3,
    desc: "I love my family",
    photo: "/assets/posts/hawkeye.jpg",
    userId: 3,
    like: 80,
    comment: 40,
    date: "24 mins ago",
  },
  {
    id: 4,
    desc: "I am always angry",
    photo: "/assets/posts/hulkpost.jpg",
    userId: 4,
    like: 91,
    comment: 52,
    date: "36 mins ago",
  },
  {
    id: 5,
    desc: "I am loki of asgard",
    photo: "/assets/posts/lokipic.jpg",
    userId: 5,
    like: 66,
    comment: 24,
    date: "49 mins ago",
  },
  {
    id: 6,
    desc: "Space is my playground",
    photo: "/assets/posts/captainmarvel.jpg",
    userId: 6,
    like: 77,
    comment: 42,
    date: "55 mins ago",
  },
  {
    id: 7,
    desc: "I am a poser",
    photo: "/assets/posts/blackwidow.jpg",
    userId: 7,
    like: 120,
    comment: 61,
    date: "1 hr ago",
  },
  {
    id: 8,
    desc: "I am immortal",
    photo: "/assets/posts/deadpool.jpg",
    userId: 8,
    like: 79,
    comment: 47,
    date: "1 hr 14 mins",
  },
  {
    id: 9,
    desc: "Expect disappointment so you won't be disappointed",
    photo: "/assets/posts/spiderman.jpg",
    userId: 9,
    like: 106,
    comment: 59,
    date: "1 hr 38 mins",
  },
  {
    id: 10,
    desc: "I love music",
    photo: "/assets/posts/starlord.jpg",
    userId: 10,
    like: 85,
    comment: 59,
    date: "1 hr 50 mins",
  },
  {
    id: 11,
    desc: "I love Christine",
    photo: "/assets/posts/docstrange.jpg",
    userId: 11,
    like: 134,
    comment: 84,
    date: "2 hrs ago",
  },
  {
    id: 12,
    desc: "Bring me Thanos",
    photo: "/assets/posts/thorpic.webp",
    userId: 12,
    like: 168,
    comment: 80,
    date: "4 hrs ago",
  },
  {
    id: 13,
    desc: "I am ironman",
    photo: "/assets/posts/ironman.jpg",
    userId: 13,
    like: 198,
    comment: 103,
    date: "12 hrs ago",
  },
  {
    id: 14,
    desc: "Me being Reasonable",
    photo: "/assets/posts/scarletwitch.jpg",
    userId: 14,
    like: 134,
    comment: 76,
    date: "4 January 2023",
  },
  {
    id: 15,
    desc: "I am a mutant",
    photo: "/assets/posts/wolverine.jpg",
    userId: 15,
    like: 123,
    comment: 91,
    date: "2 January 2023",
  },
];

export const profileFeed = [
  {
    id: 1,
    desc: "sun flower shines like the sun",
    photo: "/assets/profilePics/1.jpg",
    userId: 16,
    like: 170,
    comment: 101,
    date: "3 hrs ago",
  },
  {
    id: 2,
    desc: "adorable",
    photo: "/assets/profilePics/2.jpg",
    userId: 16,
    like: 140,
    comment: 91,
    date: "5 hrs ago",
  },
  {
    id: 3,
    desc: "Cutie cattie",
    photo: "/assets/profilePics/3.jpg",
    userId: 16,
    like: 160,
    comment: 121,
    date: "12 hrs ago",
  },
];
